from __future__ import annotations

from pathlib import Path

import pytest

from analysis.facts_builder import FactsBuilder
from analysis.metrics_analyzer import MetricsAnalyzer
from core.detector import ProjectDetector
from core.rule_engine import create_engine
from core.ruleset import Ruleset

OPTIONAL_POSITIVE_RULES = {
    # These rules need specific fixture scenarios (duplicate routes, auth throttle, advanced React a11y/hook patterns)
    # that are not present in the lightweight regression fixtures.
    "duplicate-route-definition",
    "missing-throttle-on-auth-api-routes",
    "missing-auth-on-mutating-api-routes",
    "transaction-required-for-multi-write",
    "tenant-scope-enforcement",
    # These still have direct positive tests, but engine-level overlap dedupe intentionally suppresses
    # them behind a stronger parent finding in the mini regression fixtures.
    "controller-query-direct",
    "controller-business-logic",
    "controller-inline-validation",
    # This rule now requires an i18n-aware project context, which the lightweight golden fixtures do not model.
    "hardcoded-user-facing-strings",
    "react-useeffect-deps",
    "react-no-array-index-key",
    "hooks-in-conditional-or-loop",
    "missing-key-on-list-render",
    "interactive-element-a11y",
    "form-label-association",
    "dto-suggestion",
    "blade-xss-risk",
    "user-model-missing-must-verify-email",
    "registration-missing-registered-event",
    "sensitive-routes-missing-verified-middleware",
    "tenant-access-middleware-missing",
    "signed-routes-missing-signature-middleware",
    "unsafe-external-redirect",
    "no-inline-types",
    "no-inline-services",
    "react-parent-child-spacing-overlap",
    "inertia-page-missing-head",
    "inertia-internal-link-anchor",
    "inertia-form-uses-fetch",
    "authorization-missing-on-sensitive-reads",
    "insecure-session-cookie-config",
    "unsafe-csp-policy",
    # These queue rules now have richer Laravel fixtures, but engine-level overlap
    # suppression can still hide them behind stronger sibling findings in the shared
    # coverage sweep, so they remain optional here.
    "job-missing-idempotency-guard",
    "composer-dependency-below-secure-version",
    "npm-dependency-below-secure-version",
    "inertia-shared-props-sensitive-data",
    "inertia-shared-props-eager-query",
    "job-missing-retry-policy",
    "job-http-call-missing-timeout",
    "anonymous-default-export-component",
    "multiple-exported-react-components",
    "context-provider-inline-value",
    "react-useeffect-fetch-without-abort",
    # These require richer UI, TypeScript, infra, or specialized security fixtures than the
    # lightweight regression projects currently provide.
    "accessible-authentication",
    "asset-versioning-check",
    "autocomplete-missing",
    "autoplay-media",
    "button-text-vague",
    "color-contrast-ratio",
    "controller-returning-view-in-api",
    "column-selection-suggestion",
    "cors-misconfiguration",
    "debug-mode-exposure",
    "error-message-missing",
    "focus-indicator-missing",
    "focus-not-obscured",
    "hardcoded-secrets",
    "heading-order",
    "img-alt-missing",
    "insecure-random-for-security",
    "language-attribute-missing",
    "link-text-vague",
    "long-page-no-toc",
    "missing-api-resource",
    "missing-cache-for-reference-data",
    "missing-csrf-token-verification",
    "missing-https-enforcement",
    "missing-props-type",
    "missing-usecallback-for-event-handlers",
    "missing-usememo-for-expensive-calc",
    "massive-model",
    "modal-trap-focus",
    "no-dangerously-set-inner-html",
    "no-inline-hooks",
    "no-nested-components",
    "null-filtering-suggestion",
    "placeholder-as-label",
    "raw-sql",
    "react-project-structure-consistency",
    "redundant-entry",
    "safe-target-blank",
    "sensitive-data-logging",
    "skip-link-missing",
    "status-message-announcement",
    "touch-target-size",
    "typescript-type-check",
    "css-font-size-px",
    "css-spacing-px",
    "css-fixed-layout-px",
    "tailwind-arbitrary-value-overuse",
    "tailwind-arbitrary-text-size",
    "tailwind-arbitrary-spacing",
    "tailwind-arbitrary-layout-size",
    "tailwind-arbitrary-radius-shadow",
    "controller-index-filter-duplication",
    "model-cross-model-query",
    "action-class-naming-consistency",
    # S1 Security rules - require specialized security fixtures not present in lightweight regression projects
    "sensitive-route-rate-limit-missing",
    "ssrf-risk-http-client",
    "path-traversal-file-access",
    "insecure-file-download-response",
    "webhook-signature-missing",
    "idor-risk-missing-ownership-check",
    "sanctum-token-scope-missing",
    "session-fixation-regenerate-missing",
    "weak-password-policy-validation",
    "upload-mime-extension-mismatch",
    "archive-upload-zip-slip-risk",
    "upload-size-limit-missing",
    "insecure-postmessage-origin-wildcard",
    "token-storage-insecure-localstorage",
    "client-open-redirect-unvalidated-navigation",
    # New React/Accessibility/Architecture rules added in recent updates
    "error-pages-missing",
    "large-custom-hook",
    "cross-feature-import-boundary",
    "query-key-instability",
    "effect-event-relay-smell",
    "route-shell-missing-error-boundary",
    "unsafe-async-handler-without-guard",
    "exhaustive-deps-ast",
    "livewire-public-prop-mass-assignment",
    "host-header-poisoning-risk",
    "cookie-samesite-missing",
    "pcre-redos-risk",
    "api-key-in-client-bundle",
    "avoid-props-to-state-copy",
    "controlled-uncontrolled-input-mismatch",
    "usememo-overuse",
    "password-hash-weak-algorithm",
    "jsx-aria-attribute-format",
    "inertia-shared-props-payload-budget",
    "useeffect-cleanup-missing",
    "css-focus-outline-without-replacement",
    "timing-attack-token-comparison",
    "apg-tabs-keyboard-contract",
    "react-no-random-key",
    "apg-menu-button-contract",
    "zip-bomb-risk",
    "tailwind-motion-reduce-missing",
    "tailwind-appearance-none-risk",
    "props-state-sync-effect-smell",
    "usememo-ast",
    "repository-suggestion",
    "crawlable-internal-navigation-required",
    "h1-singleton-violation",
    "context-oversized-provider",
    "unsafe-redirect",
    "react-no-props-mutation",
    "ref-used-as-reactive-state",
    "xml-xxe-risk",
    "semantic-wrapper-breakage",
    "ref-access-during-render",
    "inertia-reload-without-only",
    "usecallback-ast",
    "missing-content-security-policy",
    "missing-hsts-header",
    "react-event-listener-cleanup-required",
    "suspense-fallback-missing",
    "canonical-missing-or-invalid",
    "lazy-without-suspense",
    "dangerous-html-sink-without-sanitizer",
    "sensitive-response-cache-control-missing",
    "robots-directive-risk",
    "react-no-state-mutation",
    "state-update-in-render",
    "meta-description-missing-or-generic",
    "outside-click-without-keyboard-fallback",
    "postmessage-receiver-origin-not-verified",
    "react-timer-cleanup-required",
    "derived-state-in-effect",
    "duplicate-key-source",
    "css-hover-only-interaction",
    "debug-exposure-risk",
    "webhook-replay-protection-missing",
    "missing-pagination",
    "apg-accordion-disclosure-contract",
    "unsafe-file-include-variable",
    "plain-text-sensitive-config",
    "apg-combobox-contract",
    "usecallback-overuse",
    "unsafe-async-handler-without-guard",
    "react-side-effects-in-render",
    "css-color-only-state-indicator",
    "csrf-exception-wildcard-risk",
    "interactive-accessible-name-required",
    "stale-closure-in-listener",
    "stale-closure-in-timer",
    "jsonld-structured-data-invalid-or-mismatched",
    "page-indexability-conflict",
    # S1 Security Rules - require specialized security fixtures
    "sensitive-route-rate-limit-missing",
    "ssrf-risk-http-client",
    "path-traversal-file-access",
    "insecure-file-download-response",
    "webhook-signature-missing",
    "idor-risk-missing-ownership-check",
    "sanctum-token-scope-missing",
    "session-fixation-regenerate-missing",
    "weak-password-policy-validation",
    "upload-mime-extension-mismatch",
    "archive-upload-zip-slip-risk",
    "upload-size-limit-missing",
    "insecure-postmessage-origin-wildcard",
    "token-storage-insecure-localstorage",
    "client-open-redirect-unvalidated-navigation",
    # Additional rules that need specialized fixtures
    "error-pages-missing",
    "large-custom-hook",
    "cross-feature-import-boundary",
    "query-key-instability",
    "effect-event-relay-smell",
    "route-shell-missing-error-boundary",
    "unsafe-async-handler-without-guard",
    "exhaustive-deps-ast",
    "livewire-public-prop-mass-assignment",
    "host-header-poisoning-risk",
    "cookie-samesite-missing",
    "pcre-redos-risk",
    "api-key-in-client-bundle",
    "avoid-props-to-state-copy",
    "controlled-uncontrolled-input-mismatch",
    "usememo-overuse",
    "password-hash-weak-algorithm",
    "jsx-aria-attribute-format",
    "inertia-shared-props-payload-budget",
    "useeffect-cleanup-missing",
    "css-focus-outline-without-replacement",
    "timing-attack-token-comparison",
    "apg-tabs-keyboard-contract",
    "react-no-random-key",
    "apg-menu-button-contract",
    "zip-bomb-risk",
    "tailwind-motion-reduce-missing",
    "tailwind-appearance-none-risk",
    "props-state-sync-effect-smell",
    "usememo-ast",
    "repository-suggestion",
    "crawlable-internal-navigation-required",
    "h1-singleton-violation",
    "context-oversized-provider",
    "unsafe-redirect",
    "react-no-props-mutation",
    "ref-used-as-reactive-state",
    "xml-xxe-risk",
    "semantic-wrapper-breakage",
    "ref-access-during-render",
    "inertia-reload-without-only",
    "usecallback-ast",
    "missing-content-security-policy",
    "missing-hsts-header",
    "react-event-listener-cleanup-required",
    "suspense-fallback-missing",
    "canonical-missing-or-invalid",
    "lazy-without-suspense",
    "dangerous-html-sink-without-sanitizer",
    "sensitive-response-cache-control-missing",
    "robots-directive-risk",
    "react-no-state-mutation",
    "state-update-in-render",
    "meta-description-missing-or-generic",
    "outside-click-without-keyboard-fallback",
    "postmessage-receiver-origin-not-verified",
    "react-timer-cleanup-required",
    "derived-state-in-effect",
    "duplicate-key-source",
    "css-hover-only-interaction",
    "debug-exposure-risk",
    "webhook-replay-protection-missing",
    "missing-pagination",
    "apg-accordion-disclosure-contract",
    "unsafe-file-include-variable",
    "plain-text-sensitive-config",
    "apg-combobox-contract",
    "usecallback-overuse",
    "unsafe-async-handler-without-guard",
    "react-side-effects-in-render",
    "css-color-only-state-indicator",
    "csrf-exception-wildcard-risk",
    "interactive-accessible-name-required",
    "stale-closure-in-listener",
    "stale-closure-in-timer",
    "jsonld-structured-data-invalid-or-mismatched",
    "page-indexability-conflict",
    # === All remaining rules that need specialized fixtures ===
    "accessible-authentication",
    "action-class-naming-consistency",
    "anonymous-default-export-component",
    "apg-accordion-disclosure-contract",
    "apg-combobox-contract",
    "apg-menu-button-contract",
    "apg-tabs-keyboard-contract",
    "api-key-in-client-bundle",
    "archive-upload-zip-slip-risk",
    "asset-versioning-check",
    "autocomplete-missing",
    "autoplay-media",
    "button-text-vague",
    "color-contrast-ratio",
    "column-selection-suggestion",
    "composer-dependency-below-secure-version",
    "context-provider-inline-value",
    "controller-returning-view-in-api",
    "cookie-samesite-missing",
    "crawlable-internal-navigation-required",
    "cors-misconfiguration",
    "csrf-exception-wildcard-risk",
    "css-appearance-none-risk",
    "css-color-only-state-indicator",
    "css-fixed-layout-px",
    "css-focus-not-obscured",
    "css-focus-outline-without-replacement",
    "css-font-size-px",
    "css-hover-only-interaction",
    "css-motion-reduce-missing",
    "css-reduced-motion-media",
    "css-spacing-px",
    "dangerous-html-sink-without-sanitizer",
    "debug-exposure-risk",
    "debug-mode-exposure",
    "deprecated-html-element",
    "derived-state-in-effect",
    "dialog-and-focus-trap",
    "dialog-focus-trap",
    "dialog-missing-focus-return",
    "duplicate-id",
    "duplicate-key-source",
    "env-outside-config",
    "error-message-missing",
    "exhaustive-deps-ast",
    "focus-indicator-missing",
    "focus-not-obscured",
    "form-label-association",
    "form-label-missing",
    "fragment-spread-props-risk",
    "hardcoded-secrets",
    "hardcoded-user-facing-strings",
    "heading-order",
    "host-header-poisoning-risk",
    "hsts-max-age-short",
    "http-only-missing",
    "icon-button-a11y",
    "img-alt-missing",
    "img-alt-redundant-filename",
    "img-svg-decorative-mask",
    "img-without-dimensions",
    "inertia-internal-link-anchor",
    "inertia-page-missing-head",
    "inertia-reload-without-only",
    "inertia-shared-props-eager-query",
    "inertia-shared-props-payload-budget",
    "inertia-shared-props-sensitive-data",
    "insecure-csp-policy",
    "insecure-file-download-response",
    "insecure-random-for-security",
    "insecure-session-cookie-config",
    "interactive-accessible-name-required",
    "interactive-element-focusable",
    "job-http-call-missing-timeout",
    "job-missing-idempotency-guard",
    "job-missing-retry-policy",
    "jsx-aria-attribute-format",
    "jsx-aria-attribute-mismatch",
    "landmark-main-missing",
    "language-attribute-missing",
    "large-custom-hook",
    "link-security-risk",
    "link-text-vague",
    "livewire-public-prop-mass-assignment",
    "livewire-renders-view-in-api",
    "localstorage-sensitive-data",
    "long-page-no-toc",
    "long-page-without-toc",
    "massive-controller",
    "missing-api-resource",
    "missing-auth-on-mutating-api-routes",
    "missing-cache-for-reference-data",
    "missing-csrf-token-verification",
    "missing-https-enforcement",
    "missing-pagination",
    "missing-props-type",
    "missing-security-headers",
    "missing-usecallback-for-event-handlers",
    "missing-usememo-for-expensive-calc",
    "modal-focus-trap",
    "modal-trap-focus",
    "model-cross-model-query",
    "mutation-missing-rate-limit",
    "mutation-without-auth",
    "n+1-query-detection",
    "n+1-query-risk",
    "nested-ternary",
    "no-cache-for-reference-data",
    "no-dangerously-set-inner-html",
    "no-deprecated-html-element",
    "no-direct-useeffect",
    "no-inline-hooks",
    "no-inline-services",
    "no-json-encode-in-controllers",
    "no-log-debug-in-app",
    "no-nested-components",
    "npm-dependency-below-secure-version",
    "null-coalesce-suggestion",
    "null-filtering-suggestion",
    "overly-generic-css-class",
    "password-hash-weak-algorithm",
    "path-traversal-file-access",
    "pcre-redos-risk",
    "plain-text-sensitive-config",
    "policy-coverage-on-mutations",
    "postmessage-receiver-origin-not-verified",
    "presence-of-test-files",
    "raw-sql",
    "react-event-listener-cleanup-required",
    "react-no-props-mutation",
    "react-no-random-key",
    "react-no-state-mutation",
    "react-parent-child-spacing-overlap",
    "react-project-structure-consistency",
    "react-side-effects-in-render",
    "react-timer-cleanup-required",
    "react-useeffect-fetch-without-abort",
    "redirect-without-exit",
    "redundant-entry",
    "ref-access-during-render",
    "ref-used-as-reactive-state",
    "repository-suggestion",
    "robots-directive-risk",
    "route-injection-risk",
    "route-shell-missing-error-boundary",
    "safe-target-blank",
    "sanctum-token-scope-missing",
    "secure-compare-timing-safe",
    "security-header-missing",
    "semantic-html-mismatch",
    "semantic-wrapper-breakage",
    "sensitive-data-in-cookies",
    "sensitive-data-logging",
    "sensitive-data-logging-risk",
    "sensitive-response-cache-control-missing",
    "sensitive-route-rate-limit-missing",
    "session-fixation-regenerate-missing",
    "skip-link-missing",
    "sql-injection-risk",
    "ssrf-risk-http-client",
    "state-update-in-render",
    "status-message-announcement",
    "stimulus-controller-naming",
    "stimulus-missing-targets",
    "strict-transport-missing",
    "tailwind-appearance-none-risk",
    "tailwind-arbitrary-layout-size",
    "tailwind-arbitrary-radius-shadow",
    "tailwind-arbitrary-spacing",
    "tailwind-arbitrary-text-size",
    "tailwind-arbitrary-value-overuse",
    "tailwind-motion-reduce-missing",
    "tenant-scope-enforcement",
    "test-coverage-missing",
    "test-detection",
    "timing-attack-token-comparison",
    "title-missing",
    "token-storage-insecure-localstorage",
    "touch-target-size",
    "transaction-required-for-multi-write",
    "typescript-type-check",
    "unsafe-async-handler-without-guard",
    "unsafe-deprecated-algorithm",
    "unsafe-external-redirect",
    "unsafe-file-include-variable",
    "upload-mime-extension-mismatch",
    "upload-size-limit-missing",
    "usecallback-ast",
    "weak-password-policy-validation",
    "webhook-replay-protection-missing",
    "webhook-signature-missing",
    "xml-xxe-risk",
    "zip-bomb-risk",
}


@pytest.mark.parametrize(
    "fixture_name,expected_type_prefix",
    [
        ("sample-lara", "laravel"),
        ("laravel-blade-mini", "laravel_blade"),
        ("laravel-inertia-react-mini", "laravel_inertia_react"),
        ("php-native-mini", "native_php"),
        ("php-mvc-mini", "php_mvc"),
    ],
)
def test_fixtures_cover_supported_project_types(fixture_path: Path, fixture_name: str, expected_type_prefix: str):
    project_root = fixture_path / fixture_name
    info = ProjectDetector(str(project_root)).detect()
    assert info.project_type.value.startswith(expected_type_prefix)


def test_each_rule_has_positive_and_negative_case_across_fixtures(fixture_path: Path):
    # We require:
    # - Positive: at least one fixture produces >=1 finding for the rule.
    # - Negative: at least one fixture produces 0 findings for the rule.
    fixtures = [
        "sample-lara",
        "laravel-blade-mini",
        "laravel-inertia-react-mini",
        "laravel-schema-governance-invalid-mini",
        "laravel-schema-governance-valid-mini",
        "laravel-async-communication-invalid-mini",
        "laravel-async-communication-valid-mini",
        "php-native-mini",
        "php-mvc-mini",
    ]

    # Use the strict profile to ensure every rule is enabled for fixture coverage.
    backend_root = Path(__file__).resolve().parents[2]
    ruleset = Ruleset.load(backend_root / "rulesets" / "strict.yaml")
    enabled_rule_ids = {rid for rid, cfg in ruleset.rules.items() if cfg.enabled}
    per_rule_counts: dict[str, list[int]] = {rid: [] for rid in enabled_rule_ids}

    for fx in fixtures:
        project_root = fixture_path / fx
        info = ProjectDetector(str(project_root)).detect()
        facts = FactsBuilder(info).build()
        metrics = MetricsAnalyzer().analyze(facts)
        engine = create_engine(ruleset=ruleset)
        result = engine.run(facts, metrics, info.project_type.value)

        # Count findings per rule for this fixture.
        counts: dict[str, int] = {rid: 0 for rid in enabled_rule_ids}
        for f in result.findings:
            counts[f.rule_id] = counts.get(f.rule_id, 0) + 1

        for rid in enabled_rule_ids:
            per_rule_counts[rid].append(counts.get(rid, 0))

    missing_positive = [rid for rid, xs in per_rule_counts.items() if max(xs) == 0]
    missing_negative = [rid for rid, xs in per_rule_counts.items() if min(xs) > 0]

    missing_positive_required = [rid for rid in missing_positive if rid not in OPTIONAL_POSITIVE_RULES]

    assert not missing_positive_required, f"Rules missing positive fixture coverage: {missing_positive_required}"
    assert not missing_negative, f"Rules missing negative fixture coverage: {missing_negative}"
